### ISSUE TITLE
你好，我想问一下怎么在自己的数据上进行实例分割测试呢？

### ISSUE THREAD

**Issue by Yellowshuohahaha** [YanjieZe/pointgroup#1]
刚入门这个领域。。。我有一个pcd的点云，里面包含了几个实例部件，怎么使用pointgroup在这上面进行实例分割测试呢，方便给一些指导吗？非常感谢！

**Comment by YanjieZe** [comment]
I think you could refer this repo, which contains some basic guidance: https://github.com/dvlab-research/PointGroup
